### ISSUE TITLE
is it possible to batch requests?

### ISSUE THREAD

**Issue by seiyria** [goldfire/gameanalytics-node-sdk#1]
For example, if I'm tracking a lot of stuff, I probably only want to flush the buffer once in a while, but would like to track it all normally in my code. 

Some examples:
- visiting a merchant and buying items multiple times,
- killing a particular group of monsters,

I can probably think of others.

**Comment by goldfire** [comment]
All calls of `track` are batched and flushed every 10 seconds (https://github.com/goldfire/gameanalytics-node-sdk/blob/master/src/index.js#L126). Or are you referring to something else?

**Comment by seiyria** [comment]
Perfect. That's exactly what I was looking for and I missed it. Thank you!
